// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDbzrF85oGlvNtlpb9kPHjXDe-EaU_wKqo',
    appId: '1:893243753130:web:ba8711c62f118e615686d3',
    messagingSenderId: '893243753130',
    projectId: 'message-in-a-bottle-7ebe4',
    authDomain: 'message-in-a-bottle-7ebe4.firebaseapp.com',
    storageBucket: 'message-in-a-bottle-7ebe4.appspot.com',
    measurementId: 'G-WDFH5JH5ZF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD6JN5JBcooOYZ0K1Yeg6eWtzeeylAtuuY',
    appId: '1:893243753130:android:8a3860be2585ca8f5686d3',
    messagingSenderId: '893243753130',
    projectId: 'message-in-a-bottle-7ebe4',
    storageBucket: 'message-in-a-bottle-7ebe4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC8x1NU97SMYg4l8tGpKzYT-58TaIyYFC0',
    appId: '1:893243753130:ios:46c6646aca1b7bbe5686d3',
    messagingSenderId: '893243753130',
    projectId: 'message-in-a-bottle-7ebe4',
    storageBucket: 'message-in-a-bottle-7ebe4.appspot.com',
    iosBundleId: 'com.example.messageInABottle',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC8x1NU97SMYg4l8tGpKzYT-58TaIyYFC0',
    appId: '1:893243753130:ios:46c6646aca1b7bbe5686d3',
    messagingSenderId: '893243753130',
    projectId: 'message-in-a-bottle-7ebe4',
    storageBucket: 'message-in-a-bottle-7ebe4.appspot.com',
    iosBundleId: 'com.example.messageInABottle',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDbzrF85oGlvNtlpb9kPHjXDe-EaU_wKqo',
    appId: '1:893243753130:web:7045a0cf88a4d5995686d3',
    messagingSenderId: '893243753130',
    projectId: 'message-in-a-bottle-7ebe4',
    authDomain: 'message-in-a-bottle-7ebe4.firebaseapp.com',
    storageBucket: 'message-in-a-bottle-7ebe4.appspot.com',
    measurementId: 'G-ZT34JCT19V',
  );

}